name: author-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: make install
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Generate key
        run: php artisan key:generate --env=testing
      - name: Run linter
        run: make lint
      - name: Run tests
        if: always()
        run: make test
      - name: Run test & publish code coverage
        if: always()
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          XDEBUG_MODE: coverage
        with:
          coverageCommand: make test-coverage
          debug: true
